version: '3'
services:
  aws:
    image: ramu478/aws
    ports:
      - "81:80"
    deploy:
      replicas: 3

  devops:
    image: ramu478/devops
    ports:
      - "82:80"
    deploy:
      replicas: 3

  java:
    image: ramu478/java
    ports:
      - "83:80"
    deploy:
      replicas: 3

  python:
    image: ramu478/python
    ports:
      - "84:80"
    deploy:
      replicas: 3
